# This file is part of PulseAudio.
#
# PulseAudio is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of the
# License, or (at your option) any later version.
#
# PulseAudio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.

[General]
priority = 70
description-key=analog-input

[Element Input Gain Control]
volume = 2

[Element What U Hear]
switch = mute
volume = merge
override-map.1 = all
override-map.2 = all-left,all-right

[Element PCM Capture Source]
enumeration = select

[Option PCM Capture Source:What U Hear]
name = "What U Hear"
required-any = any

[Element Line In]
switch = off
volume = off

[Element External Mic]
switch = off
volume = off

[Element S/PDIF In]
switch = off
volume = off